<?php

$toEngArray = array(
                    "TCS-PLACE" => "Tentative Computer Science Placement",
                    "CS-PLACEMENT" => "Computer Science Placement",
                    "MATH-PLACEMENT" => "Math Placement",
                    "STAT-PLACEMENT" => "Statistics Placement",
                    "TMATH-PLACE" => "Tentative Math Placement",
                    "TSTAT-PLACE" => "Tentative Statistics Placement",
                    "AdjSemOfMath" => "Adjusted Semesters of Math",
                    "actcomp" => "ACT Comprehensive",
                    "actmath" => "ACT Mathematics",
                    "satmath" => "SAT Mathematics",
		    "satmathreal" => "SAT Math (Adjusted)",
                    "sat2math1" => "SAT II Math Level-1",
                    "sat2math2" => "SAT II Math Level-2",
                    "sat2math2adj" => "SAT II Math Level-2 Adjusted",
                    "totalyears" => "Total years ",
                    "precalcsem" => "Semesters of Pre-Calculus",
                    "precalcgrade" => "Pre-Calculus Grade",
                    "calcsem" => "Semesters of Calculus",
                    "calgrade" => "Calculus Grade",
                    "statsem" => "Semesters of Statistics",
                    "statgrade" => "Statistics Grade",
                    "mathsem" => "Semesters of Math",
                    "apcalcbc" => "AP Calculus BC",
                    "apcsab" => "AP Computer Science AB",
                    "apcsa" => "AP Computer Science A",
                    "apstat" => "AP Statistics",
                    "apcalcab" => "AP Calculus AB",
                    "ibcs" => "IB Comp Sci.",
                    "ibmat" => "IB Mathematics",
                    "alevelf" => "A level F",
                    "alevelp" => "A level P",
                    "stdscores" => "standardized test scores",
                    "csgrade" => "Computer Science grade",
                    "cssem" => "Semesters of Computer Science",
                    "=" => "is");
?>
